# Generated by Django 2.1.15 on 2020-06-17 04:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('original_title', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('runtime', models.IntegerField()),
                ('poster_path', models.TextField()),
                ('overview', models.TextField()),
                ('adult', models.BooleanField()),
                ('award', models.BooleanField()),
                ('keywords', models.CharField(max_length=100)),
                ('director', models.CharField(max_length=100)),
                ('actors', models.TextField()),
                ('produce_year', models.CharField(max_length=30)),
                ('nation', models.CharField(max_length=30)),
                ('rating', models.CharField(max_length=30)),
                ('isboxoffice', models.BooleanField()),
                ('stills', models.TextField()),
                ('genres', models.ManyToManyField(related_name='movies', to='movies.Genre')),
                ('like', models.ManyToManyField(related_name='like_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Survey_movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('poster_path', models.TextField()),
                ('genres', models.ManyToManyField(related_name='survey_movies', to='movies.Genre')),
            ],
        ),
    ]
